#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
sxhkd &
picom --experimental-backends  --config  /home/user/.config/picom/picom.conf &
nitrogen --restore 
#dunst &
polybar --config /home/user/.config/polybar/config.ini &
#These are custom configs based on my needs,feel free to change.

lxpolkit &

$HOME/.config/polybar/launch.sh

pkill ibus-daemon

bspc config focused_border_color "#d4cbef"

bspc rule -a Spotube state=tiled

#bspc rule -a kitty state=floating

bspc rule -a TelegramDesktop state=floating

bspc rule -a Gnome-calculator state=floating

export FILE_MANAGER=thunar

xsetroot -cursor_name left_ptr

